package net.microwww.rurl.domain;

import java.io.Serializable;
import java.util.*;
import javax.persistence.*;
import net.microwww.common.BeanContextFactory;
import net.microwww.rurl.repository.AccountRepository;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "account")
public class Account implements Serializable {

    public static List<Webapp> listAccountLoginApps(String account) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public static Account getByAccount(String account) {
        return getRepository().getByAccount(account);
    }

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(columnDefinition = "INT UNSIGNED")
    private int id;

    @Basic
    @Column(nullable = false, length = 45)
    private String account;

    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "create_time", columnDefinition = "TIMESTAMP", nullable = false)
    private Date createTime = new Date();

    @Basic
    @Column(length = 45)
    private String email;

    @Basic
    @Column(length = 45)
    private String name;

    @Basic
    @Column(length = 45)
    private String phone;

    public Account() {
    }

    public Account(int id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    protected static AccountRepository getRepository() {
        return BeanContextFactory.get().getBean(AccountRepository.class);
    }

    public static Account getById(int id) {
        return getRepository().getById(id);
    }
}
