package net.microwww.rurl.domain;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;
import net.microwww.common.BeanContextFactory;
import net.microwww.rurl.repository.AccountGroupsRepository;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "account_groups")
public class AccountGroups implements Serializable {

    public static List<Account> listAccountByGroup(Groups gp) {
        return getRepository().findAccountByGroupsId(gp.getId());
    }

    public static AccountGroups getByAccountIdGroupsId(int aid, int gid) {
        return getRepository().getByAccountIdGroupsId(aid, gid);
    }

    public static List<AccountGroups> findByGroupsId(int id) {
        return getRepository().findByGroupsId(id);
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(columnDefinition = "INT UNSIGNED")
    private int id;

    /**
     * 账户回被同步保存!
     */
    @ManyToOne(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH}, optional = false)
    @JoinColumn(name = "account_id", referencedColumnName = "id")
    private Account account;

    @Basic
    @Column(nullable = false, length = 45)
    private String name;

    @ManyToOne(cascade = {CascadeType.REFRESH}, optional = false)
    @JoinColumn(name = "groups_id", referencedColumnName = "id")
    private Groups groups;

    public AccountGroups() {
    }

    public AccountGroups(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
        this.name = this.account.getAccount();
    }

    public Groups getGroups() {
        return groups;
    }

    public void setGroups(Groups groups) {
        this.groups = groups;
    }

    public String getName() {
        return name;
    }

    public void setName(String accountName) {
        //this.name = accountName;
    }

    protected static AccountGroupsRepository getRepository() {
        return BeanContextFactory.get().getBean(AccountGroupsRepository.class);
    }

    public static AccountGroups getById(int id) {
        return getRepository().getById(id);
    }
}
