package net.microwww.rurl.domain;

import java.io.Serializable;
import java.util.*;
import javax.persistence.*;
import net.microwww.common.BeanContextFactory;
import net.microwww.rurl.repository.GroupsRepository;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "groups")
public class Groups implements Serializable {

    public static List<Groups> listGroups() {
        return getRepository().findAll();
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(columnDefinition = "INT UNSIGNED")
    private int id;

    @Basic
    @Column(name = "create_time", columnDefinition = "TIMESTAMP", nullable = false)
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date createTime = new Date();

    @Basic
    private String data;

    @Basic
    @Column(length = 1000)
    private String discrption;

    @Basic
    @Column(nullable = false, length = 45)
    private String name;

    public Groups() {
    }

    public Groups(int id) {
        this.id = id;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getDiscrption() {
        return discrption;
    }

    public void setDiscrption(String discrption) {
        this.discrption = discrption;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    protected static GroupsRepository getRepository() {
        return BeanContextFactory.get().getBean(GroupsRepository.class);
    }

    public static Groups getById(int id) {
        return getRepository().getById(id);
    }
}
