package net.microwww.rurl.repository;

import java.util.List;
import net.microwww.rurl.domain.Groups;
import org.springframework.data.repository.Repository;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public interface GroupsRepository extends Repository<Groups, Integer> {

    public Groups getById(int id);

    public List<Groups> findAll();
}
