package net.microwww.rurl.repository;

import java.util.List;
import net.microwww.rurl.domain.Groups;
import net.microwww.rurl.domain.WebappurlGroups;
import net.microwww.rurl.domain.Webapp;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public interface WebappurlGroupsRepository extends Repository<WebappurlGroups, Integer> {

    public WebappurlGroups getById(int id);

    public List<WebappurlGroups> findAll();

    public List<WebappurlGroups> findByGroupsId(int id);

    @Query("select distinct(u.webapp) from WebappurlGroups as u where u.groups.id = ?1")
    public List<Webapp> findWebappByGroupsId(int id);

    @Query("select distinct(u.groups) from WebappurlGroups as u where u.webapp.id = ?1")
    public List<Groups> findGroupsByWebapp(int id);

    @Query("select u from WebappurlGroups as u where u.groups.id = ?1 and u.webappurl.id = ?2")
    public WebappurlGroups getByGroupsIdWebappurlId(int gid, int uid);
}
