package net.microwww.rurl.repository;

import java.util.List;
import net.microwww.rurl.domain.Webapp;
import net.microwww.rurl.domain.Webappurl;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public interface WebappRepository extends Repository<Webapp, Integer> {

    public Webapp getById(int id);

    public List<Webapp> findAll();

    public Webapp getByAppName(String appname);

    @Query(value = "select distinct wg.webappurl from AccountGroups ag, WebappurlGroups wg "
            + "where ag.groups.id = wg.groups.id and ag.account.id = ?1")
    public List<Webappurl> findRightByAccountId(int id);

    @Query(value = "select distinct wg.webappurl from AccountGroups ag, WebappurlGroups wg "
            + "where ag.groups.id = wg.groups.id and ag.account.id = ?1 and wg.webappurl.webapp.id = ?2")
    public List<Webappurl> findRightByAccountIdWebappId(int id, int webappid);
}
