package net.microwww.rurl.repository;

import java.util.List;
import net.microwww.rurl.domain.Webappurl;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.Repository;

/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
public interface WebappurlRepository extends Repository<Webappurl, Integer> {

    public Webappurl getById(int id);

    public List<Webappurl> findAll();

    @Query("select u.webappurl from WebappurlGroups as u where u.groups.id = ?1 and u.webapp.id = ?2")
    public List<Webappurl> findByGroupsIdWebappId(int gid, int wid);

    public List<Webappurl> findByWebappId(int id);

    @Query("select u.webappurl from WebappurlGroups as u where u.groups.id = ?1")
    public List<Webappurl> findByGroupsId(int id);

    public List<Webappurl> findByWebappPath(String path);
}
